import {
  TalentTreeNodeCreateWithoutSpecializationInput,
  Photon,
  Talent,
  Specialization,
  TalentTreeNodeCreateconnectionsInput,
  TalentCreateOneWithoutTalentInput,
} from '@prisma/photon';
import * as TALENT from './constants/talents';
import * as SPECS from './constants/specializations';

/*
  {
    row: 1,
    column: 1,
    talent: { connect: { id:  } },
    connections: { set: [] },
  },
  {
    row: 1,
    column: 2,
    talent: { connect: { id:  } },
    connections: { set: [] },
  },
  {
    row: 1,
    column: 3,
    talent: { connect: { id:  } },
    connections: { set: [] },
  },
  {
    row: 1,
    column: 4,
    talent: { connect: { id:  } },
    connections: { set: [] },
  },
  {
    row: 2,
    column: 1,
    talent: { connect: { id:  } },
    connections: { set: [] },
  },
  {
    row: 2,
    column: 2,
    talent: { connect: { id:  } },
    connections: { set: [] },
  },
  {
    row: 2,
    column: 3,
    talent: { connect: { id:  } },
    connections: { set: [] },
  },
  {
    row: 2,
    column: 4,
    talent: { connect: { id:  } },
    connections: { set: [] },
  },
  {
    row: 3,
    column: 1,
    talent: { connect: { id:  } },
    connections: { set: [] },
  },
  {
    row: 3,
    column: 2,
    talent: { connect: { id:  } },
    connections: { set: [] },
  },
  {
    row: 3,
    column: 3,
    talent: { connect: { id:  } },
    connections: { set: [] },
  },
  {
    row: 3,
    column: 4,
    talent: { connect: { id:  } },
    connections: { set: [] },
  },
  {
    row: 4,
    column: 1,
    talent: { connect: { id:  } },
    connections: { set: [] },
  },
  {
    row: 4,
    column: 2,
    talent: { connect: { id:  } },
    connections: { set: [] },
  },
  {
    row: 4,
    column: 3,
    talent: { connect: { id:  } },
    connections: { set: [] },
  },
  {
    row: 4,
    column: 4,
    talent: { connect: { id:  } },
    connections: { set: [] },
  },
  {
    row: 5,
    column: 1,
    talent: { connect: { id:  } },
    connections: { set: [] },
  },
  {
    row: 5,
    column: 2,
    talent: { connect: { id:  } },
    connections: { set: [] },
  },
  {
    row: 5,
    column: 3,
    talent: { connect: { id:  } },
    connections: { set: [] },
  },
  {
    row: 5,
    column: 4,
    talent: { connect: { id:  } },
    connections: { set: [] },
  },
*/

const UP = 1;
const RIGHT = 2;
const DOWN = 3;
const LEFT = 4;

interface TalentTreeNodeCreate {
  row: number;
  column: number;
  connections: TalentTreeNodeCreateconnectionsInput;
  talent: TalentCreateOneWithoutTalentInput;
}

interface TalentTreeUpdate {
  specialization: number;
  talents: TalentTreeNodeCreate[];
}

export interface TalentTreeResponse {
  id: string;
  row: number;
  column: number;
  talent: Talent;
  specialization: Specialization;
}

const talentTrees: TalentTreeUpdate[] = [
  {
    specialization: SPECS.DRIVER,
    talents: [
      {
        row: 1,
        column: 1,
        connections: { set: [DOWN] },
        talent: { connect: { id: TALENT.FULL_THROTTLE } },
      },
      {
        row: 1,
        column: 2,
        connections: { set: [] },
        talent: { connect: { id: TALENT.ALL_TERRAIN_DRIVER } },
      },
      {
        row: 1,
        column: 3,
        connections: { set: [] },
        talent: { connect: { id: TALENT.FINE_TUNING } },
      },
      {
        row: 1,
        column: 4,
        connections: { set: [DOWN] },
        talent: { connect: { id: TALENT.GEARHEAD } },
      },
      {
        row: 2,
        column: 1,
        connections: { set: [UP, RIGHT, DOWN] },
        talent: { connect: { id: TALENT.GRIT } },
      },
      {
        row: 2,
        column: 2,
        connections: { set: [RIGHT, DOWN, LEFT] },
        talent: { connect: { id: TALENT.SKILLED_JOCKEY } },
      },
      {
        row: 2,
        column: 3,
        connections: { set: [RIGHT, LEFT] },
        talent: { connect: { id: TALENT.RAPID_REACTION } },
      },
      {
        row: 2,
        column: 4,
        connections: { set: [UP, DOWN, LEFT] },
        talent: { connect: { id: TALENT.GRIT } },
      },
      {
        row: 3,
        column: 1,
        connections: { set: [UP, DOWN] },
        talent: { connect: { id: TALENT.IMPROVED_FULL_THROTTLE } },
      },
      {
        row: 3,
        column: 2,
        connections: { set: [UP] },
        talent: { connect: { id: TALENT.TRICKY_TARGET } },
      },
      {
        row: 3,
        column: 3,
        connections: { set: [RIGHT] },
        talent: { connect: { id: TALENT.FINE_TUNING } },
      },
      {
        row: 3,
        column: 4,
        connections: { set: [UP, DOWN, LEFT] },
        talent: { connect: { id: TALENT.TOUGHENED } },
      },
      {
        row: 4,
        column: 1,
        connections: { set: [UP, RIGHT, DOWN] },
        talent: { connect: { id: TALENT.DEFENSIVE_DRIVING } },
      },
      {
        row: 4,
        column: 2,
        connections: { set: [RIGHT, LEFT] },
        talent: { connect: { id: TALENT.SKILLED_JOCKEY } },
      },
      {
        row: 4,
        column: 3,
        connections: { set: [LEFT] },
        talent: { connect: { id: TALENT.NATURAL_DRIVER } },
      },
      {
        row: 4,
        column: 4,
        connections: { set: [UP, DOWN] },
        talent: { connect: { id: TALENT.GEARHEAD } },
      },
      {
        row: 5,
        column: 1,
        connections: { set: [UP, RIGHT] },
        talent: { connect: { id: TALENT.SUPREME_FULL_THROTTLE } },
      },
      {
        row: 5,
        column: 2,
        connections: { set: [RIGHT, LEFT] },
        talent: { connect: { id: TALENT.FULL_STOP } },
      },
      {
        row: 5,
        column: 3,
        connections: { set: [RIGHT, LEFT] },
        talent: { connect: { id: TALENT.MASTER_DRIVER } },
      },
      {
        row: 5,
        column: 4,
        connections: { set: [UP, LEFT] },
        talent: { connect: { id: TALENT.DEDICATION } },
      },
    ],
  },
  {
    specialization: SPECS.GUNNER,
    talents: [
      {
        row: 1,
        column: 1,
        connections: { set: [DOWN] },
        talent: { connect: { id: TALENT.DURABLE } },
      },
      {
        row: 1,
        column: 2,
        connections: { set: [] },
        talent: { connect: { id: TALENT.GRIT } },
      },
      {
        row: 1,
        column: 3,
        connections: { set: [DOWN] },
        talent: { connect: { id: TALENT.OVERWHELM_DEFENSES } },
      },
      {
        row: 1,
        column: 4,
        connections: { set: [DOWN] },
        talent: { connect: { id: TALENT.DEBILITATING_SHOT } },
      },
      {
        row: 2,
        column: 1,
        connections: { set: [UP, RIGHT] },
        talent: { connect: { id: TALENT.TOUGHENED } },
      },
      {
        row: 2,
        column: 2,
        connections: { set: [RIGHT, DOWN, LEFT] },
        talent: { connect: { id: TALENT.BRACE } },
      },
      {
        row: 2,
        column: 3,
        connections: { set: [UP, DOWN, LEFT] },
        talent: { connect: { id: TALENT.SPARE_CLIP } },
      },
      {
        row: 2,
        column: 4,
        connections: { set: [UP, DOWN] },
        talent: { connect: { id: TALENT.TRUE_AIM } },
      },
      {
        row: 3,
        column: 1,
        connections: { set: [RIGHT, DOWN] },
        talent: { connect: { id: TALENT.DURABLE } },
      },
      {
        row: 3,
        column: 2,
        connections: { set: [UP, LEFT] },
        talent: { connect: { id: TALENT.ENDURING } },
      },
      {
        row: 3,
        column: 3,
        connections: { set: [UP, DOWN] },
        talent: { connect: { id: TALENT.JURY_RIGGED } },
      },
      {
        row: 3,
        column: 4,
        connections: { set: [UP, DOWN] },
        talent: { connect: { id: TALENT.OVERWHELM_DEFENSES } },
      },
      {
        row: 4,
        column: 1,
        connections: { set: [UP, RIGHT, DOWN] },
        talent: { connect: { id: TALENT.TOUGHENED } },
      },
      {
        row: 4,
        column: 2,
        connections: { set: [RIGHT, DOWN, LEFT] },
        talent: { connect: { id: TALENT.ENDURING } },
      },
      {
        row: 4,
        column: 3,
        connections: { set: [UP, LEFT] },
        talent: { connect: { id: TALENT.BRACE } },
      },
      {
        row: 4,
        column: 4,
        connections: { set: [UP, DOWN] },
        talent: { connect: { id: TALENT.EXHAUST_PORT } },
      },
      {
        row: 5,
        column: 1,
        connections: { set: [UP, RIGHT] },
        talent: { connect: { id: TALENT.HEROIC_FORTITUDE } },
      },
      {
        row: 5,
        column: 2,
        connections: { set: [UP, RIGHT, LEFT] },
        talent: { connect: { id: TALENT.JURY_RIGGED } },
      },
      {
        row: 5,
        column: 3,
        connections: { set: [RIGHT, LEFT] },
        talent: { connect: { id: TALENT.DEDICATION } },
      },
      {
        row: 5,
        column: 4,
        connections: { set: [UP, LEFT] },
        talent: { connect: { id: TALENT.TRUE_AIM } },
      },
    ],
  },
  {
    specialization: SPECS.PILOT,
    talents: [
      {
        row: 1,
        column: 1,
        talent: { connect: { id: TALENT.FULL_THROTTLE } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 2,
        talent: { connect: { id: TALENT.SKILLED_JOCKEY } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 3,
        talent: { connect: { id: TALENT.GALAXY_MAPPER } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 4,
        talent: { connect: { id: TALENT.LETS_RIDE } },
        connections: { set: [DOWN] },
      },
      {
        row: 2,
        column: 1,
        talent: { connect: { id: TALENT.SKILLED_JOCKEY } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 2,
        column: 2,
        talent: { connect: { id: TALENT.DEAD_TO_RIGHTS } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 2,
        column: 3,
        talent: { connect: { id: TALENT.GALAXY_MAPPER } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 2,
        column: 4,
        talent: { connect: { id: TALENT.RAPID_RECOVERY } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 3,
        column: 1,
        talent: { connect: { id: TALENT.IMPROVED_FULL_THROTTLE } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 2,
        talent: { connect: { id: TALENT.IMPROVED_DEAD_TO_RIGHTS } },
        connections: { set: [UP] },
      },
      {
        row: 3,
        column: 3,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 3,
        column: 4,
        talent: { connect: { id: TALENT.NATURAL_PILOT } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 4,
        column: 1,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 4,
        column: 2,
        talent: { connect: { id: TALENT.SUPREME_FULL_THROTTLE } },
        connections: { set: [LEFT] },
      },
      {
        row: 4,
        column: 3,
        talent: { connect: { id: TALENT.TRICKY_TARGET } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 4,
        column: 4,
        talent: { connect: { id: TALENT.DEFENSIVE_DRIVING } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 5,
        column: 1,
        talent: { connect: { id: TALENT.MASTER_PILOT } },
        connections: { set: [UP, RIGHT] },
      },
      {
        row: 5,
        column: 2,
        talent: { connect: { id: TALENT.DEDICATION } },
        connections: { set: [RIGHT, LEFT] },
      },
      {
        row: 5,
        column: 3,
        talent: { connect: { id: TALENT.TOUGHENED } },
        connections: { set: [UP, RIGHT, LEFT] },
      },
      {
        row: 5,
        column: 4,
        talent: { connect: { id: TALENT.BRILLIANT_EVASION } },
        connections: { set: [UP, LEFT] },
      },
    ],
  },
  {
    specialization: SPECS.COMMODORE,
    talents: [
      {
        row: 1,
        column: 1,
        talent: { connect: { id: TALENT.SOLID_REPAIRS } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 2,
        talent: { connect: { id: TALENT.COMMAND } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 3,
        talent: { connect: { id: TALENT.RAPID_REACTION } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 4,
        talent: { connect: { id: TALENT.GALAXY_MAPPER } },
        connections: { set: [DOWN] },
      },
      {
        row: 2,
        column: 1,
        talent: { connect: { id: TALENT.KNOWN_SCHEMATICS } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 2,
        column: 2,
        talent: { connect: { id: TALENT.COMMANDING_PRESENCE } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 2,
        column: 3,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 2,
        column: 4,
        talent: { connect: { id: TALENT.FAMILIAR_SUNS } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 1,
        talent: { connect: { id: TALENT.SOLID_REPAIRS } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 2,
        talent: { connect: { id: TALENT.COMMAND } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 3,
        talent: { connect: { id: TALENT.RAPID_REACTION } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 4,
        talent: { connect: { id: TALENT.GALAXY_MAPPER } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 4,
        column: 1,
        talent: { connect: { id: TALENT.HOLD_TOGETHER } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 4,
        column: 2,
        talent: { connect: { id: TALENT.COMMANDING_PRESENCE } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 4,
        column: 3,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 4,
        column: 4,
        talent: { connect: { id: TALENT.MASTER_STARHOPPER } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 5,
        column: 1,
        talent: { connect: { id: TALENT.SOLID_REPAIRS } },
        connections: { set: [UP, RIGHT] },
      },
      {
        row: 5,
        column: 2,
        talent: { connect: { id: TALENT.FIRE_CONTROL } },
        connections: { set: [UP, RIGHT, LEFT] },
      },
      {
        row: 5,
        column: 3,
        talent: { connect: { id: TALENT.DEDICATION } },
        connections: { set: [UP, RIGHT, LEFT] },
      },
      {
        row: 5,
        column: 4,
        talent: { connect: { id: TALENT.GALAXY_MAPPER } },
        connections: { set: [UP, LEFT] },
      },
    ],
  },
  {
    specialization: SPECS.SQUADRON_LEADER,
    talents: [
      {
        row: 1,
        column: 1,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 2,
        talent: { connect: { id: TALENT.QUICK_STRIKE } },
        connections: { set: [] },
      },
      {
        row: 1,
        column: 3,
        talent: { connect: { id: TALENT.LETS_RIDE } },
        connections: { set: [] },
      },
      {
        row: 1,
        column: 4,
        talent: { connect: { id: TALENT.DEFENSIVE_DRIVING } },
        connections: { set: [DOWN] },
      },
      {
        row: 2,
        column: 1,
        talent: { connect: { id: TALENT.FIELD_COMMANDER } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 2,
        column: 2,
        talent: { connect: { id: TALENT.CONFIDENCE } },
        connections: { set: [LEFT, DOWN] },
      },
      {
        row: 2,
        column: 3,
        talent: { connect: { id: TALENT.QUICK_STRIKE } },
        connections: { set: [RIGHT, DOWN] },
      },
      {
        row: 2,
        column: 4,
        talent: { connect: { id: TALENT.SITUATIONAL_AWARENESS } },
        connections: { set: [UP, LEFT] },
      },
      {
        row: 3,
        column: 1,
        talent: { connect: { id: TALENT.COMMAND } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 2,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 3,
        talent: { connect: { id: TALENT.FULL_STOP } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 4,
        talent: { connect: { id: TALENT.DEFENSIVE_DRIVING } },
        connections: { set: [DOWN] },
      },
      {
        row: 4,
        column: 1,
        talent: { connect: { id: TALENT.IMPROVED_FIELD_COMMANDER } },
        connections: { set: [UP] },
      },
      {
        row: 4,
        column: 2,
        talent: { connect: { id: TALENT.COMMAND } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 4,
        column: 3,
        talent: { connect: { id: TALENT.FORM_ON_ME } },
        connections: { set: [UP, RIGHT, DOWN, LEFT] },
      },
      {
        row: 4,
        column: 4,
        talent: { connect: { id: TALENT.TRICKY_TARGET } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 5,
        column: 1,
        talent: { connect: { id: TALENT.MASTER_LEADER } },
        connections: { set: [RIGHT] },
      },
      {
        row: 5,
        column: 2,
        talent: { connect: { id: TALENT.CONFIDENCE } },
        connections: { set: [UP, RIGHT] },
      },
      {
        row: 5,
        column: 3,
        talent: { connect: { id: TALENT.DEDICATION } },
        connections: { set: [UP] },
      },
      {
        row: 5,
        column: 4,
        talent: { connect: { id: TALENT.BRILLIANT_EVASION } },
        connections: { set: [UP] },
      },
    ],
  },
  {
    specialization: SPECS.TACTICIAN,
    talents: [
      {
        row: 1,
        column: 1,
        talent: { connect: { id: TALENT.OUTDOORSMAN } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 2,
        talent: { connect: { id: TALENT.COMMANDING_PRESENCE } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 3,
        talent: { connect: { id: TALENT.TOUGHENED } },
        connections: { set: [] },
      },
      {
        row: 1,
        column: 4,
        talent: { connect: { id: TALENT.SIDE_STEP } },
        connections: { set: [DOWN] },
      },
      {
        row: 2,
        column: 1,
        talent: { connect: { id: TALENT.OUTDOORSMAN } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 2,
        column: 2,
        talent: { connect: { id: TALENT.CONFIDENCE } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 2,
        column: 3,
        talent: { connect: { id: TALENT.QUICK_DRAW } },
        connections: { set: [RIGHT] },
      },
      {
        row: 2,
        column: 4,
        talent: { connect: { id: TALENT.SWIFT } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 3,
        column: 1,
        talent: { connect: { id: TALENT.NATURAL_OUTDOORSMAN } },
        connections: { set: [UP] },
      },
      {
        row: 3,
        column: 2,
        talent: { connect: { id: TALENT.TOUGHENED } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 3,
        column: 3,
        talent: { connect: { id: TALENT.BODY_GUARD } },
        connections: { set: [RIGHT, LEFT] },
      },
      {
        row: 3,
        column: 4,
        talent: { connect: { id: TALENT.BODY_GUARD } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 4,
        column: 1,
        talent: { connect: { id: TALENT.CONFIDENCE } },
        connections: { set: [RIGHT] },
      },
      {
        row: 4,
        column: 2,
        talent: { connect: { id: TALENT.COMMANDING_PRESENCE } },
        connections: { set: [UP, RIGHT, DOWN, LEFT] },
      },
      {
        row: 4,
        column: 3,
        talent: { connect: { id: TALENT.FIELD_COMMANDER } },
        connections: { set: [DOWN, LEFT] },
      },
      {
        row: 4,
        column: 4,
        talent: { connect: { id: TALENT.SIDE_STEP } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 5,
        column: 1,
        talent: { connect: { id: TALENT.COORDINATED_ASSAULT } },
        connections: { set: [RIGHT] },
      },
      {
        row: 5,
        column: 2,
        talent: { connect: { id: TALENT.NATURAL_LEADER } },
        connections: { set: [UP, LEFT] },
      },
      {
        row: 5,
        column: 3,
        talent: { connect: { id: TALENT.IMPROVED_FIELD_COMMANDER } },
        connections: { set: [UP] },
      },
      {
        row: 5,
        column: 4,
        talent: { connect: { id: TALENT.DEDICATION } },
        connections: { set: [UP] },
      },
    ],
  },
  {
    specialization: SPECS.AMBASSADOR,
    talents: [
      {
        row: 1,
        column: 1,
        talent: { connect: { id: TALENT.INDISTINGUISHABLE } },
        connections: { set: [] },
      },
      {
        row: 1,
        column: 2,
        talent: { connect: { id: TALENT.KILL_WITH_KINDNESS } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 3,
        talent: { connect: { id: TALENT.NOBODYS_FOOL } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 4,
        talent: { connect: { id: TALENT.CONFIDENCE } },
        connections: { set: [DOWN] },
      },
      {
        row: 2,
        column: 1,
        talent: { connect: { id: TALENT.INDISTINGUISHABLE } },
        connections: { set: [RIGHT] },
      },
      {
        row: 2,
        column: 2,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 2,
        column: 3,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 2,
        column: 4,
        talent: { connect: { id: TALENT.DODGE } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 1,
        talent: { connect: { id: TALENT.KILL_WITH_KINDNESS } },
        connections: { set: [RIGHT, DOWN] },
      },
      {
        row: 3,
        column: 2,
        talent: { connect: { id: TALENT.INSPIRING_RHETORIC } },
        connections: { set: [UP, RIGHT, DOWN, LEFT] },
      },
      {
        row: 3,
        column: 3,
        talent: { connect: { id: TALENT.STEELY_NERVES } },
        connections: { set: [UP, RIGHT, LEFT] },
      },
      {
        row: 3,
        column: 4,
        talent: { connect: { id: TALENT.CONFIDENCE } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 4,
        column: 1,
        talent: { connect: { id: TALENT.IMPROVED_INSPIRING_RHETORIC } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 4,
        column: 2,
        talent: { connect: { id: TALENT.INTENSE_PRESENCE } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 4,
        column: 3,
        talent: { connect: { id: TALENT.WORKS_LIKE_A_CHARM } },
        connections: { set: [LEFT] },
      },
      {
        row: 4,
        column: 4,
        talent: { connect: { id: TALENT.DODGE } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 5,
        column: 1,
        talent: { connect: { id: TALENT.SUPREME_INSPIRING_RHETORIC } },
        connections: { set: [UP] },
      },
      {
        row: 5,
        column: 2,
        talent: { connect: { id: TALENT.NATURAL_CHARMER } },
        connections: { set: [UP, RIGHT] },
      },
      {
        row: 5,
        column: 3,
        talent: { connect: { id: TALENT.DEDICATION } },
        connections: { set: [RIGHT, LEFT] },
      },
      {
        row: 5,
        column: 4,
        talent: { connect: { id: TALENT.SIXTH_SENSE } },
        connections: { set: [UP, LEFT] },
      },
    ],
  },
  {
    specialization: SPECS.AGITATOR,
    talents: [
      {
        row: 1,
        column: 1,
        talent: { connect: { id: TALENT.PLAUSIBLE_DENIABILITY } },
        connections: { set: [] },
      },
      {
        row: 1,
        column: 2,
        talent: { connect: { id: TALENT.NOBODYS_FOOL } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 3,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 4,
        talent: { connect: { id: TALENT.INTIMIDATING } },
        connections: { set: [] },
      },
      {
        row: 2,
        column: 1,
        talent: { connect: { id: TALENT.STREET_SMARTS } },
        connections: { set: [DOWN] },
      },
      {
        row: 2,
        column: 2,
        talent: { connect: { id: TALENT.STREET_SMARTS } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 2,
        column: 3,
        talent: { connect: { id: TALENT.CONVINCING_DEMEANOR } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 2,
        column: 4,
        talent: { connect: { id: TALENT.INTIMIDATING } },
        connections: { set: [DOWN] },
      },
      {
        row: 3,
        column: 1,
        talent: { connect: { id: TALENT.CONVINCING_DEMEANOR } },
        connections: { set: [UP, RIGHT] },
      },
      {
        row: 3,
        column: 2,
        talent: { connect: { id: TALENT.PLAUSIBLE_DENIABILITY } },
        connections: { set: [UP, DOWN, RIGHT, LEFT] },
      },
      {
        row: 3,
        column: 3,
        talent: { connect: { id: TALENT.SCATHING_TIRADE } },
        connections: { set: [UP, DOWN, LEFT, RIGHT] },
      },
      {
        row: 3,
        column: 4,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [UP, LEFT] },
      },
      {
        row: 4,
        column: 1,
        talent: { connect: { id: TALENT.NATURAL_ENFORCER } },
        connections: { set: [RIGHT, DOWN] },
      },
      {
        row: 4,
        column: 2,
        talent: { connect: { id: TALENT.NOBODYS_FOOL } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 4,
        column: 3,
        talent: { connect: { id: TALENT.IMPROVED_SCATHING_TIRADE } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 4,
        column: 4,
        talent: { connect: { id: TALENT.INTIMIDATING } },
        connections: { set: [LEFT, DOWN] },
      },
      {
        row: 5,
        column: 1,
        talent: { connect: { id: TALENT.INTIMIDATING } },
        connections: { set: [UP] },
      },
      {
        row: 5,
        column: 2,
        talent: { connect: { id: TALENT.DEDICATION } },
        connections: { set: [UP] },
      },
      {
        row: 5,
        column: 3,
        talent: { connect: { id: TALENT.SUPREME_SCATHING_TIRADE } },
        connections: { set: [UP] },
      },
      {
        row: 5,
        column: 4,
        talent: { connect: { id: TALENT.INCITE_REBELLION } },
        connections: { set: [UP] },
      },
    ],
  },
  {
    specialization: SPECS.QUARTERMASTER,
    talents: [
      {
        row: 1,
        column: 1,
        talent: { connect: { id: TALENT.KNOW_SOMEBODY } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 2,
        talent: { connect: { id: TALENT.SMOOTH_TALKER } },
        connections: { set: [] },
      },
      {
        row: 1,
        column: 3,
        talent: { connect: { id: TALENT.WHEEL_AND_DEAL } },
        connections: { set: [] },
      },
      {
        row: 1,
        column: 4,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [DOWN] },
      },
      {
        row: 2,
        column: 1,
        talent: { connect: { id: TALENT.SMOOTH_TALKER } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 2,
        column: 2,
        talent: { connect: { id: TALENT.GREASED_PALMS } },
        connections: { set: [RIGHT, DOWN] },
      },
      {
        row: 2,
        column: 3,
        talent: { connect: { id: TALENT.MASTER_MERCHANT } },
        connections: { set: [DOWN, LEFT] },
      },
      {
        row: 2,
        column: 4,
        talent: { connect: { id: TALENT.TOUGHENED } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 1,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 2,
        talent: { connect: { id: TALENT.WHEEL_AND_DEAL } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 3,
        column: 3,
        talent: { connect: { id: TALENT.BOUGHT_INFO } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 3,
        column: 4,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 4,
        column: 1,
        talent: { connect: { id: TALENT.KNOW_SOMEBODY } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 4,
        column: 2,
        talent: { connect: { id: TALENT.SOUND_INVESTMENTS } },
        connections: { set: [UP, RIGHT, LEFT] },
      },
      {
        row: 4,
        column: 3,
        talent: { connect: { id: TALENT.SOUND_INVESTMENTS } },
        connections: { set: [UP, LEFT] },
      },
      {
        row: 4,
        column: 4,
        talent: { connect: { id: TALENT.INTENSE_FOCUS } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 5,
        column: 1,
        talent: { connect: { id: TALENT.DEDICATION } },
        connections: { set: [UP, RIGHT] },
      },
      {
        row: 5,
        column: 2,
        talent: { connect: { id: TALENT.NATURAL_NEGOTIATOR } },
        connections: { set: [LEFT] },
      },
      {
        row: 5,
        column: 3,
        talent: { connect: { id: TALENT.SUPERIOR_REFLEXES } },
        connections: { set: [RIGHT] },
      },
      {
        row: 5,
        column: 4,
        talent: { connect: { id: TALENT.TOUGHENED } },
        connections: { set: [UP, LEFT] },
      },
    ],
  },
  {
    specialization: SPECS.MECHANIC,
    talents: [
      {
        row: 1,
        column: 1,
        talent: { connect: { id: TALENT.GEARHEAD } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 2,
        talent: { connect: { id: TALENT.TOUGHENED } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 3,
        talent: { connect: { id: TALENT.FINE_TUNING } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 4,
        talent: { connect: { id: TALENT.SOLID_REPAIRS } },
        connections: { set: [DOWN] },
      },
      {
        row: 2,
        column: 1,
        talent: { connect: { id: TALENT.REDUNDANT_SYSTEMS } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 2,
        column: 2,
        talent: { connect: { id: TALENT.SOLID_REPAIRS } },
        connections: { set: [UP, RIGHT, DOWN, LEFT] },
      },
      {
        row: 2,
        column: 3,
        talent: { connect: { id: TALENT.GEARHEAD } },
        connections: { set: [UP, RIGHT, DOWN, LEFT] },
      },
      {
        row: 2,
        column: 4,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 3,
        column: 1,
        talent: { connect: { id: TALENT.SOLID_REPAIRS } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 3,
        column: 2,
        talent: { connect: { id: TALENT.ENDURING } },
        connections: { set: [UP, RIGHT, DOWN, LEFT] },
      },
      {
        row: 3,
        column: 3,
        talent: { connect: { id: TALENT.BAD_MOTIVATOR } },
        connections: { set: [UP, RIGHT, DOWN, LEFT] },
      },
      {
        row: 3,
        column: 4,
        talent: { connect: { id: TALENT.TOUGHENED } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 4,
        column: 1,
        talent: { connect: { id: TALENT.CONTRAPTION } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 4,
        column: 2,
        talent: { connect: { id: TALENT.SOLID_REPAIRS } },
        connections: { set: [UP, RIGHT, DOWN, LEFT] },
      },
      {
        row: 4,
        column: 3,
        talent: { connect: { id: TALENT.FINE_TUNING } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 4,
        column: 4,
        talent: { connect: { id: TALENT.HARD_HEADED } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 5,
        column: 1,
        talent: { connect: { id: TALENT.NATURAL_TINKERER } },
        connections: { set: [UP] },
      },
      {
        row: 5,
        column: 2,
        talent: { connect: { id: TALENT.HOLD_TOGETHER } },
        connections: { set: [UP] },
      },
      {
        row: 5,
        column: 3,
        talent: { connect: { id: TALENT.DEDICATION } },
        connections: { set: [UP] },
      },
      {
        row: 5,
        column: 4,
        talent: { connect: { id: TALENT.IMPROVED_HARD_HEADED } },
        connections: { set: [UP] },
      },
    ],
  },
  {
    specialization: SPECS.SABOTEUR,
    talents: [
      {
        row: 1,
        column: 1,
        talent: { connect: { id: TALENT.RESOLVE } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 2,
        talent: { connect: { id: TALENT.SECOND_WIND } },
        connections: { set: [] },
      },
      {
        row: 1,
        column: 3,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [] },
      },
      {
        row: 1,
        column: 4,
        talent: { connect: { id: TALENT.RAPID_RECOVERY } },
        connections: { set: [DOWN] },
      },
      {
        row: 2,
        column: 1,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [UP, RIGHT] },
      },
      {
        row: 2,
        column: 2,
        talent: { connect: { id: TALENT.POWERFUL_BLAST } },
        connections: { set: [RIGHT, DOWN, LEFT] },
      },
      {
        row: 2,
        column: 3,
        talent: { connect: { id: TALENT.TOUGHENED } },
        connections: { set: [RIGHT, DOWN, LEFT] },
      },
      {
        row: 2,
        column: 4,
        talent: { connect: { id: TALENT.SECOND_WIND } },
        connections: { set: [UP, LEFT] },
      },
      {
        row: 3,
        column: 1,
        talent: { connect: { id: TALENT.TIME_TO_GO } },
        connections: { set: [RIGHT, DOWN] },
      },
      {
        row: 3,
        column: 2,
        talent: { connect: { id: TALENT.RAPID_RECOVERY } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 3,
        column: 3,
        talent: { connect: { id: TALENT.RESOLVE } },
        connections: { set: [UP, RIGHT] },
      },
      {
        row: 3,
        column: 4,
        talent: { connect: { id: TALENT.HARD_HEADED } },
        connections: { set: [DOWN, LEFT] },
      },
      {
        row: 4,
        column: 1,
        talent: { connect: { id: TALENT.IMPROVED_TIME_TO_GO } },
        connections: { set: [UP] },
      },
      {
        row: 4,
        column: 2,
        talent: { connect: { id: TALENT.POWERFUL_BLAST } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 4,
        column: 3,
        talent: { connect: { id: TALENT.SELECTIVE_DETONATION } },
        connections: { set: [DOWN, LEFT] },
      },
      {
        row: 4,
        column: 4,
        talent: { connect: { id: TALENT.TOUGHENED } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 5,
        column: 1,
        talent: { connect: { id: TALENT.DEDICATION } },
        connections: { set: [RIGHT] },
      },
      {
        row: 5,
        column: 2,
        talent: { connect: { id: TALENT.MASTER_GRENADIER } },
        connections: { set: [UP, LEFT] },
      },
      {
        row: 5,
        column: 3,
        talent: { connect: { id: TALENT.SELECTIVE_DETONATION } },
        connections: { set: [UP] },
      },
      {
        row: 5,
        column: 4,
        talent: { connect: { id: TALENT.IMPROVED_HARD_HEADED } },
        connections: { set: [UP] },
      },
    ],
  },
  {
    specialization: SPECS.SCIENTIST,
    talents: [
      {
        row: 1,
        column: 1,
        talent: { connect: { id: TALENT.KNOWLEDGE_SPECIALIZATION } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 2,
        talent: { connect: { id: TALENT.RESPECTED_SCHOLAR } },
        connections: { set: [] },
      },
      {
        row: 1,
        column: 3,
        talent: { connect: { id: TALENT.RESEARCHER } },
        connections: { set: [] },
      },
      {
        row: 1,
        column: 4,
        talent: { connect: { id: TALENT.SPEAKS_BINARY } },
        connections: { set: [DOWN] },
      },
      {
        row: 2,
        column: 1,
        talent: { connect: { id: TALENT.RESEARCHER } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 2,
        column: 2,
        talent: { connect: { id: TALENT.KNOWLEDGE_SPECIALIZATION } },
        connections: { set: [LEFT] },
      },
      {
        row: 2,
        column: 3,
        talent: { connect: { id: TALENT.HIDDEN_STORAGE } },
        connections: { set: [RIGHT] },
      },
      {
        row: 2,
        column: 4,
        talent: { connect: { id: TALENT.TINKERER } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 3,
        column: 1,
        talent: { connect: { id: TALENT.RESPECTED_SCHOLAR } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 3,
        column: 2,
        talent: { connect: { id: TALENT.MENTAL_FORTRESS } },
        connections: { set: [RIGHT] },
      },
      {
        row: 3,
        column: 3,
        talent: { connect: { id: TALENT.SPEAKS_BINARY } },
        connections: { set: [RIGHT] },
      },
      {
        row: 3,
        column: 4,
        talent: { connect: { id: TALENT.INVENTOR } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 4,
        column: 1,
        talent: { connect: { id: TALENT.NATURAL_SCHOLAR } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 4,
        column: 2,
        talent: { connect: { id: TALENT.STROKE_OF_GENIUS } },
        connections: { set: [LEFT] },
      },
      {
        row: 4,
        column: 3,
        talent: { connect: { id: TALENT.INVENTOR } },
        connections: { set: [RIGHT] },
      },
      {
        row: 4,
        column: 4,
        talent: { connect: { id: TALENT.TINKERER } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 5,
        column: 1,
        talent: { connect: { id: TALENT.INTENSE_FOCUS } },
        connections: { set: [UP, RIGHT] },
      },
      {
        row: 5,
        column: 2,
        talent: { connect: { id: TALENT.CAREFUL_PLANNING } },
        connections: { set: [RIGHT, LEFT] },
      },
      {
        row: 5,
        column: 3,
        talent: { connect: { id: TALENT.DEDICATION } },
        connections: { set: [RIGHT, LEFT] },
      },
      {
        row: 5,
        column: 4,
        talent: { connect: { id: TALENT.UTILITY_BELT } },
        connections: { set: [UP, LEFT] },
      },
    ],
  },
  {
    specialization: SPECS.COMMANDO,
    talents: [
      {
        row: 1,
        column: 1,
        talent: { connect: { id: TALENT.PHYSICAL_TRAINING } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 2,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [] },
      },
      {
        row: 1,
        column: 3,
        talent: { connect: { id: TALENT.TOUGHENED } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 4,
        talent: { connect: { id: TALENT.POINT_BLANK } },
        connections: { set: [DOWN] },
      },
      {
        row: 2,
        column: 1,
        talent: { connect: { id: TALENT.TOUGHENED } },
        connections: { set: [UP, RIGHT] },
      },
      {
        row: 2,
        column: 2,
        talent: { connect: { id: TALENT.DURABLE } },
        connections: { set: [RIGHT, DOWN, LEFT] },
      },
      {
        row: 2,
        column: 3,
        talent: { connect: { id: TALENT.PHYSICAL_TRAINING } },
        connections: { set: [UP, RIGHT, DOWN, LEFT] },
      },
      {
        row: 2,
        column: 4,
        talent: { connect: { id: TALENT.STRONG_ARM } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 3,
        column: 1,
        talent: { connect: { id: TALENT.BLOOEDED } },
        connections: { set: [RIGHT, DOWN] },
      },
      {
        row: 3,
        column: 2,
        talent: { connect: { id: TALENT.ARMOR_MASTER } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 3,
        column: 3,
        talent: { connect: { id: TALENT.NATURAL_OUTDOORSMAN } },
        connections: { set: [UP] },
      },
      {
        row: 3,
        column: 4,
        talent: { connect: { id: TALENT.FERAL_STRENGTH } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 4,
        column: 1,
        talent: { connect: { id: TALENT.TOUGHENED } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 4,
        column: 2,
        talent: { connect: { id: TALENT.HEROIC_FORTITUDE } },
        connections: { set: [UP, RIGHT, DOWN, LEFT] },
      },
      {
        row: 4,
        column: 3,
        talent: { connect: { id: TALENT.DURABLE } },
        connections: { set: [DOWN, LEFT] },
      },
      {
        row: 4,
        column: 4,
        talent: { connect: { id: TALENT.KNOCKDOWN } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 5,
        column: 1,
        talent: { connect: { id: TALENT.IMPROVED_ARMOR_MASTER } },
        connections: { set: [UP] },
      },
      {
        row: 5,
        column: 2,
        talent: { connect: { id: TALENT.DEDICATION } },
        connections: { set: [UP] },
      },
      {
        row: 5,
        column: 3,
        talent: { connect: { id: TALENT.UNSTOPPABLE } },
        connections: { set: [UP] },
      },
      {
        row: 5,
        column: 4,
        talent: { connect: { id: TALENT.FERAL_STRENGTH } },
        connections: { set: [UP] },
      },
    ],
  },
  {
    specialization: SPECS.MEDIC,
    talents: [
      {
        row: 1,
        column: 1,
        talent: { connect: { id: TALENT.FORAGER } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 2,
        talent: { connect: { id: TALENT.STIMPACK_SPECIALIZATION } },
        connections: { set: [] },
      },
      {
        row: 1,
        column: 3,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [] },
      },
      {
        row: 1,
        column: 4,
        talent: { connect: { id: TALENT.SURGEON } },
        connections: { set: [DOWN] },
      },
      {
        row: 2,
        column: 1,
        talent: { connect: { id: TALENT.TOUGHENED } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 2,
        column: 2,
        talent: { connect: { id: TALENT.SURGEON } },
        connections: { set: [RIGHT, DOWN] },
      },
      {
        row: 2,
        column: 3,
        talent: { connect: { id: TALENT.STIMPACK_SPECIALIZATION } },
        connections: { set: [RIGHT, DOWN, LEFT] },
      },
      {
        row: 2,
        column: 4,
        talent: { connect: { id: TALENT.BACTA_SPECIALIST } },
        connections: { set: [UP, LEFT] },
      },
      {
        row: 3,
        column: 1,
        talent: { connect: { id: TALENT.WELL_ROUNDED } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 2,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 3,
        column: 3,
        talent: { connect: { id: TALENT.STIM_APPLICATION } },
        connections: { set: [UP, RIGHT, DOWN, LEFT] },
      },
      {
        row: 3,
        column: 4,
        talent: { connect: { id: TALENT.MASTER_DOCTOR } },
        connections: { set: [LEFT] },
      },
      {
        row: 4,
        column: 1,
        talent: { connect: { id: TALENT.DODGE } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 4,
        column: 2,
        talent: { connect: { id: TALENT.NATURAL_DOCTOR } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 4,
        column: 3,
        talent: { connect: { id: TALENT.IMPROVED_STIM_APPLICATION } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 4,
        column: 4,
        talent: { connect: { id: TALENT.STIMPACK_SPECIALIZATION } },
        connections: { set: [DOWN, LEFT] },
      },
      {
        row: 5,
        column: 1,
        talent: { connect: { id: TALENT.ANATOMY_LESSON } },
        connections: { set: [UP] },
      },
      {
        row: 5,
        column: 2,
        talent: { connect: { id: TALENT.DEDICATION } },
        connections: { set: [UP, RIGHT] },
      },
      {
        row: 5,
        column: 3,
        talent: { connect: { id: TALENT.ITS_NOT_THAT_BAD } },
        connections: { set: [UP, LEFT] },
      },
      {
        row: 5,
        column: 4,
        talent: { connect: { id: TALENT.SUPREME_STIM_APPLICATION } },
        connections: { set: [UP] },
      },
    ],
  },
  {
    specialization: SPECS.SHARPSHOOTER,
    talents: [
      {
        row: 1,
        column: 1,
        talent: { connect: { id: TALENT.EXPERT_TRACKER } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 2,
        talent: { connect: { id: TALENT.SNIPER_SHOT } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 3,
        talent: { connect: { id: TALENT.BRACE } },
        connections: { set: [] },
      },
      {
        row: 1,
        column: 4,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [DOWN] },
      },
      {
        row: 2,
        column: 1,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 2,
        column: 2,
        talent: { connect: { id: TALENT.TRUE_AIM } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 2,
        column: 3,
        talent: { connect: { id: TALENT.DEADLY_ACCURACY } },
        connections: { set: [DOWN] },
      },
      {
        row: 2,
        column: 4,
        talent: { connect: { id: TALENT.LETHAL_BLOWS } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 1,
        talent: { connect: { id: TALENT.BRACE } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 2,
        talent: { connect: { id: TALENT.LETHAL_BLOWS } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 3,
        column: 3,
        talent: { connect: { id: TALENT.SNIPER_SHOT } },
        connections: { set: [UP, RIGHT, LEFT] },
      },
      {
        row: 3,
        column: 4,
        talent: { connect: { id: TALENT.TRUE_AIM } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 4,
        column: 1,
        talent: { connect: { id: TALENT.EXPERT_TRACKER } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 4,
        column: 2,
        talent: { connect: { id: TALENT.DEADLY_ACCURACY } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 4,
        column: 3,
        talent: { connect: { id: TALENT.TOUGHENED } },
        connections: { set: [DOWN, LEFT] },
      },
      {
        row: 4,
        column: 4,
        talent: { connect: { id: TALENT.CRIPPLING_BLOW } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 5,
        column: 1,
        talent: { connect: { id: TALENT.QUICK_FIX } },
        connections: { set: [UP, RIGHT] },
      },
      {
        row: 5,
        column: 2,
        talent: { connect: { id: TALENT.NATURAL_MARKSMAN } },
        connections: { set: [UP, LEFT] },
      },
      {
        row: 5,
        column: 3,
        talent: { connect: { id: TALENT.DEDICATION } },
        connections: { set: [UP] },
      },
      {
        row: 5,
        column: 4,
        talent: { connect: { id: TALENT.TARGETED_BLOW } },
        connections: { set: [UP] },
      },
    ],
  },
  {
    specialization: SPECS.INFILTRATOR,
    talents: [
      {
        row: 1,
        column: 1,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [] },
      },
      {
        row: 1,
        column: 2,
        talent: { connect: { id: TALENT.DODGE } },
        connections: { set: [] },
      },
      {
        row: 1,
        column: 3,
        talent: { connect: { id: TALENT.FRENZIED_ATTACK } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 4,
        talent: { connect: { id: TALENT.DEFENSIVE_STANCE } },
        connections: { set: [DOWN] },
      },
      {
        row: 2,
        column: 1,
        talent: { connect: { id: TALENT.STUNNING_BLOW } },
        connections: { set: [RIGHT, DOWN] },
      },
      {
        row: 2,
        column: 2,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [RIGHT, LEFT] },
      },
      {
        row: 2,
        column: 3,
        talent: { connect: { id: TALENT.SOFT_SPOT } },
        connections: { set: [UP, LEFT] },
      },
      {
        row: 2,
        column: 4,
        talent: { connect: { id: TALENT.JUMP_UP } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 1,
        talent: { connect: { id: TALENT.KNOCKDOWN } },
        connections: { set: [UP, RIGHT] },
      },
      {
        row: 3,
        column: 2,
        talent: { connect: { id: TALENT.FRENZIED_ATTACK } },
        connections: { set: [RIGHT, LEFT] },
      },
      {
        row: 3,
        column: 3,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [DOWN, LEFT] },
      },
      {
        row: 3,
        column: 4,
        talent: { connect: { id: TALENT.DODGE } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 4,
        column: 1,
        talent: { connect: { id: TALENT.NATURAL_BRAWLER } },
        connections: { set: [RIGHT, DOWN] },
      },
      {
        row: 4,
        column: 2,
        talent: { connect: { id: TALENT.TOUGHENED } },
        connections: { set: [RIGHT, LEFT] },
      },
      {
        row: 4,
        column: 3,
        talent: { connect: { id: TALENT.IMPROVED_STUNNING_BLOW } },
        connections: { set: [UP, LEFT] },
      },
      {
        row: 4,
        column: 4,
        talent: { connect: { id: TALENT.DEFENSIVE_STANCE } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 5,
        column: 1,
        talent: { connect: { id: TALENT.DEDICATION } },
        connections: { set: [UP, RIGHT] },
      },
      {
        row: 5,
        column: 2,
        talent: { connect: { id: TALENT.CLEVER_SOLUTION } },
        connections: { set: [RIGHT, LEFT] },
      },
      {
        row: 5,
        column: 3,
        talent: { connect: { id: TALENT.MASTER_OF_SHADOWS } },
        connections: { set: [RIGHT, LEFT] },
      },
      {
        row: 5,
        column: 4,
        talent: { connect: { id: TALENT.NATURAL_ROGUE } },
        connections: { set: [UP, LEFT] },
      },
    ],
  },
  {
    specialization: SPECS.SCOUT,
    talents: [
      {
        row: 1,
        column: 1,
        talent: { connect: { id: TALENT.RAPID_RECOVERY } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 2,
        talent: { connect: { id: TALENT.STALKER } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 3,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 4,
        talent: { connect: { id: TALENT.SHORTCUT } },
        connections: { set: [DOWN] },
      },
      {
        row: 2,
        column: 1,
        talent: { connect: { id: TALENT.FORAGER } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 2,
        column: 2,
        talent: { connect: { id: TALENT.QUICK_STRIKE } },
        connections: { set: [UP, RIGHT, DOWN, LEFT] },
      },
      {
        row: 2,
        column: 3,
        talent: { connect: { id: TALENT.LETS_RIDE } },
        connections: { set: [UP, RIGHT, DOWN, LEFT] },
      },
      {
        row: 2,
        column: 4,
        talent: { connect: { id: TALENT.DISORIENT } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 3,
        column: 1,
        talent: { connect: { id: TALENT.RAPID_RECOVERY } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 2,
        talent: { connect: { id: TALENT.NATURAL_HUNTER } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 3,
        talent: { connect: { id: TALENT.FAMILIAR_SUNS } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 4,
        talent: { connect: { id: TALENT.SHORTCUT } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 4,
        column: 1,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 4,
        column: 2,
        talent: { connect: { id: TALENT.HEIGHTENED_AWARENESS } },
        connections: { set: [UP] },
      },
      {
        row: 4,
        column: 3,
        talent: { connect: { id: TALENT.TOUGHENED } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 4,
        column: 4,
        talent: { connect: { id: TALENT.QUICK_STRIKE } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 5,
        column: 1,
        talent: { connect: { id: TALENT.UTILITY_BELT } },
        connections: { set: [UP, RIGHT] },
      },
      {
        row: 5,
        column: 2,
        talent: { connect: { id: TALENT.DEDICATION } },
        connections: { set: [RIGHT, LEFT] },
      },
      {
        row: 5,
        column: 3,
        talent: { connect: { id: TALENT.STALKER } },
        connections: { set: [UP, LEFT] },
      },
      {
        row: 5,
        column: 4,
        talent: { connect: { id: TALENT.DISORIENT } },
        connections: { set: [UP] },
      },
    ],
  },
  {
    specialization: SPECS.SLICER,
    talents: [
      {
        row: 1,
        column: 1,
        talent: { connect: { id: TALENT.CODEBREAKER } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 2,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [] },
      },
      {
        row: 1,
        column: 3,
        talent: { connect: { id: TALENT.TECHNICAL_APTITUDE } },
        connections: { set: [] },
      },
      {
        row: 1,
        column: 4,
        talent: { connect: { id: TALENT.BYPASS_SECURITY } },
        connections: { set: [] },
      },
      {
        row: 2,
        column: 1,
        talent: { connect: { id: TALENT.DEFENSIVE_SLICING } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 2,
        column: 2,
        talent: { connect: { id: TALENT.TECHNICAL_APTITUDE } },
        connections: { set: [RIGHT, DOWN] },
      },
      {
        row: 2,
        column: 3,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [RIGHT, DOWN, LEFT] },
      },
      {
        row: 2,
        column: 4,
        talent: { connect: { id: TALENT.BYPASS_SECURITY } },
        connections: { set: [DOWN, LEFT] },
      },
      {
        row: 3,
        column: 1,
        talent: { connect: { id: TALENT.NATURAL_PROGRAMMER } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 2,
        talent: { connect: { id: TALENT.BYPASS_SECURITY } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 3,
        column: 3,
        talent: { connect: { id: TALENT.DEFENSIVE_SLICING } },
        connections: { set: [UP, RIGHT, DOWN, LEFT] },
      },
      {
        row: 3,
        column: 4,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 4,
        column: 1,
        talent: { connect: { id: TALENT.DEFENSIVE_SLICING } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 4,
        column: 2,
        talent: { connect: { id: TALENT.IMPROVED_DEFENSIVE_SLICING } },
        connections: { set: [UP, RIGHT, DOWN, LEFT] },
      },
      {
        row: 4,
        column: 3,
        talent: { connect: { id: TALENT.CODEBREAKER } },
        connections: { set: [UP, RIGHT, DOWN, LEFT] },
      },
      {
        row: 4,
        column: 4,
        talent: { connect: { id: TALENT.RESOLVE } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 5,
        column: 1,
        talent: { connect: { id: TALENT.SKILLED_SLICER } },
        connections: { set: [UP, RIGHT] },
      },
      {
        row: 5,
        column: 2,
        talent: { connect: { id: TALENT.MASTER_SLICER } },
        connections: { set: [UP, RIGHT, LEFT] },
      },
      {
        row: 5,
        column: 3,
        talent: { connect: { id: TALENT.MENTAL_FORTRESS } },
        connections: { set: [UP, RIGHT, LEFT] },
      },
      {
        row: 5,
        column: 4,
        talent: { connect: { id: TALENT.DEDICATION } },
        connections: { set: [UP, LEFT] },
      },
    ],
  },
  {
    specialization: SPECS.RECRUIT,
    talents: [
      {
        row: 1,
        column: 1,
        talent: { connect: { id: TALENT.BASIC_COMBAT_TRAINING } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 2,
        talent: { connect: { id: TALENT.SECOND_WIND } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 3,
        talent: { connect: { id: TALENT.OUTDOORSMAN } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 4,
        talent: { connect: { id: TALENT.TACTICAL_COMBAT_TRAINING } },
        connections: { set: [DOWN] },
      },
      {
        row: 2,
        column: 1,
        talent: { connect: { id: TALENT.SECOND_WIND } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 2,
        column: 2,
        talent: { connect: { id: TALENT.VEHICLE_COMBAT_TRAINING } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 2,
        column: 3,
        talent: { connect: { id: TALENT.WELL_TRAVELED } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 2,
        column: 4,
        talent: { connect: { id: TALENT.TOUGHENED } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 1,
        talent: { connect: { id: TALENT.QUICK_DRAW } },
        connections: { set: [UP, RIGHT] },
      },
      {
        row: 3,
        column: 2,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 3,
        column: 3,
        talent: { connect: { id: TALENT.TOUGHENED } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 4,
        talent: { connect: { id: TALENT.SPARE_CLIP } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 4,
        column: 1,
        talent: { connect: { id: TALENT.SECOND_WIND } },
        connections: { set: [RIGHT, DOWN] },
      },
      {
        row: 4,
        column: 2,
        talent: { connect: { id: TALENT.JUMP_UP } },
        connections: { set: [UP, RIGHT, LEFT] },
      },
      {
        row: 4,
        column: 3,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [UP, RIGHT, DOWN, LEFT] },
      },
      {
        row: 4,
        column: 4,
        talent: { connect: { id: TALENT.CREATIVE_KILLER } },
        connections: { set: [UP, LEFT] },
      },
      {
        row: 5,
        column: 1,
        talent: { connect: { id: TALENT.DYNAMIC_FIRE } },
        connections: { set: [UP, RIGHT] },
      },
      {
        row: 5,
        column: 2,
        talent: { connect: { id: TALENT.DEDICATION } },
        connections: { set: [RIGHT, LEFT] },
      },
      {
        row: 5,
        column: 3,
        talent: { connect: { id: TALENT.TOUGHENED } },
        connections: { set: [UP, RIGHT, LEFT] },
      },
      {
        row: 5,
        column: 4,
        talent: { connect: { id: TALENT.ENDURING } },
        connections: { set: [LEFT] },
      },
    ],
  },
  {
    specialization: SPECS.FORCE_SENSITIVE_EMERGENT,
    talents: [
      {
        row: 1,
        column: 1,
        talent: { connect: { id: TALENT.INSIGHT } },
        connections: { set: [] },
      },
      {
        row: 1,
        column: 2,
        talent: { connect: { id: TALENT.UNCANNY_SENSES } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 3,
        talent: { connect: { id: TALENT.INDISTINGUISHABLE } },
        connections: { set: [DOWN] },
      },
      {
        row: 1,
        column: 4,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [] },
      },
      {
        row: 2,
        column: 1,
        talent: { connect: { id: TALENT.UNCANNY_REACTIONS } },
        connections: { set: [DOWN] },
      },
      {
        row: 2,
        column: 2,
        talent: { connect: { id: TALENT.TOUGHENED } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 2,
        column: 3,
        talent: { connect: { id: TALENT.SLEIGHT_OF_MIND } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 2,
        column: 4,
        talent: { connect: { id: TALENT.SLEIGHT_OF_MIND } },
        connections: { set: [DOWN] },
      },
      {
        row: 3,
        column: 1,
        talent: { connect: { id: TALENT.UNCANNY_SENSES } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 2,
        talent: { connect: { id: TALENT.UNCANNY_REACTIONS } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 3,
        talent: { connect: { id: TALENT.GRIT } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 3,
        column: 4,
        talent: { connect: { id: TALENT.INDISTINGUISHABLE } },
        connections: { set: [UP, DOWN] },
      },
      {
        row: 4,
        column: 1,
        talent: { connect: { id: TALENT.TOUGHENED } },
        connections: { set: [UP, RIGHT, DOWN] },
      },
      {
        row: 4,
        column: 2,
        talent: { connect: { id: TALENT.SENSE_DANGER } },
        connections: { set: [UP, RIGHT, DOWN, LEFT] },
      },
      {
        row: 4,
        column: 3,
        talent: { connect: { id: TALENT.TOUCH_OF_FATE } },
        connections: { set: [UP, RIGHT, DOWN, LEFT] },
      },
      {
        row: 4,
        column: 4,
        talent: { connect: { id: TALENT.BALANCE } },
        connections: { set: [UP, DOWN, LEFT] },
      },
      {
        row: 5,
        column: 1,
        talent: { connect: { id: TALENT.INVIGORATE } },
        connections: { set: [UP] },
      },
      {
        row: 5,
        column: 2,
        talent: { connect: { id: TALENT.FORCE_OF_WILL } },
        connections: { set: [UP] },
      },
      {
        row: 5,
        column: 3,
        talent: { connect: { id: TALENT.FORCE_RATING } },
        connections: { set: [UP] },
      },
      {
        row: 5,
        column: 4,
        talent: { connect: { id: TALENT.DEDICATION } },
        connections: { set: [UP] },
      },
    ],
  },
];

export default async function(photon: Photon): Promise<TalentTreeResponse[]> {
  const allTalentTreeNodes = [];
  for (const trees of talentTrees) {
    const { specialization, talents } = trees;

    for (const talent of talents) {
      const id = `${specialization}-${talent.row}-${talent.column}`;
      const node = {
        ...talent,
        specialization: { connect: { id: specialization } },
      };
      const treeNode: TalentTreeResponse = await photon.talentTreeNodes.upsert({
        select: {
          id: true,
          row: true,
          column: true,
          talent: true,
          specialization: true,
        },
        where: { id },
        update: node,
        create: {
          id,
          ...node,
        },
      });
      console.log(`Talent Tree Node ${id} added to database`); // eslint-disable-line
      await photon.specializations.update({
        where: { id: specialization },
        data: {
          talentTree: { connect: { id: treeNode.id } },
        },
      });
      console.log( // eslint-disable-line
        `Specialization ${specialization} updated with Talent Tree Node ${id}`
      );
      allTalentTreeNodes.push(treeNode);
    }
  }

  return allTalentTreeNodes;
}
